Operator *, [] and ().
ecuadros/EDA pull request #17
Opened 2023-07-15 17:32 UTC by edson2495

Buen dia Dr. Cuadros,

Aca hago el pull request de los operadores * (para la multiplicacion),
y [], () para asignación.

Saludos.

2023-07-15 20:06 UTC, edson2495 commented
![imagen](https://github.com/ecuadros/EDA/assets/48811104/99794c03-55d4-40c1-92c1-2c3672edefcb)

2023-07-16 00:18 UTC, ecuadros requested changes

2023-07-16 00:18 UTC, ecuadros commented on matrix.h
> +            m_ppMatrix = other.m_ppMatrix;
Hay que duplicar la memoria para que realmente tengas una copia

2023-07-16 00:18 UTC, ecuadros commented on matrix.h
> +    size_t getM_rowss()
rows()

2023-07-16 00:18 UTC, ecuadros commented on matrix.h
> +    size_t getM_cols()
cols()

2023-07-16 00:18 UTC, ecuadros commented on matrix.h
> +            return m_ppMatrix[row][col].getDataRef(); //b
explore how to create operator value_type to class NodeMatrix
After that, you may remove: .getDataRef()

2023-07-16 00:18 UTC, closed without merging